### ISSUE TITLE
pyhaystack server implementation

### ISSUE THREAD

**Issue by candronikos** [ChristianTremblay/pyhaystack#52]
Just in case I missed it. Is it possible to use this library create a server that listens for haystack calls?

If not is an implementation being considered?

**Comment by sjlongland** [comment]
On 17/05/17 13:54, Christopher Andronikos wrote:
> Just in case I missed it. Is it possible to use this library create a
> server that listens for haystack calls?
> 
> If not is an implementation being considered?

Not at this time, but patches are welcome. :-)

-- 
Stuart Longland (aka Redhatter, VK4MSL)

I haven't lost my mind...
  ...it's backed up on a tape somewhere.
