### ISSUE TITLE
"refresh" not implemented on watch_poll method

### ISSUE THREAD

**Issue by itsmeccr** [ChristianTremblay/pyhaystack#59]
Although the documentation of method `def watch_poll(self, watch, refresh=False, callback=None):` has following text:
`If refresh is True, then all points on the watch will be updated, not just those that have changed since the last poll.`
, the parameter `refresh` is unused and hence above functionality as stated on documentation isn't obtained.

**Comment by itsmeccr** [comment]
[Pull request #60 ](https://github.com/ChristianTremblay/pyhaystack/pull/60)

**Comment by sjlongland** [comment]
Thanks for picking that up… I've merged it into the `develop` branch ready for the next release.
