### ISSUE TITLE
Watch_poll does not use argument refresh

### ISSUE THREAD

**Issue by Jorricks** [ChristianTremblay/pyhaystack#98]
Hello,

We are trying to set up a watch for a skyspark installation. 
I was trying to get `watch_poll` to work, however, I noticed that it always returns me all the points whether I have refresh on True or False.
I did some digging and found out it is probably due to the server implementation.

However, for a standard server, I think a full refresh won't work because of the following functions:
https://github.com/ChristianTremblay/pyhaystack/blob/master/pyhaystack/client/session.py#L510
Here it basically forgets about the refresh parameter.
```python
if refresh:
   grid.metadata["refresh"] = hszinc.MARKER
```

I think the above mentioned could should fix it if I look at the documentation specified here:
https://project-haystack.org/doc/Ops#watchPoll

**Comment by sjlongland** [comment]
Yeah, that'd be a whoopsie on my part… might've _meant_ to put those two lines in, but didn't.

**Comment by Jorricks** [comment]
Hi @sjlongland,

Thank you for adding this :)!
